### PR TITLE
Add RSS-Bridge to projects

### PR DESCRIPTION
**Pull request by mitsukarenai**

### CODE REVIEW

**Comment by artob** [comment]
Thanks!

**Comment by xirpy** [comment]
mitsukareni, so, i'm using this website that you created bridge.suumitsu.eu, rss bridge, in my bot on discord, and sometimes i receive this error "Bridge returned error 500! (17880)

[link removed]

and i want to know, if u can fix that problem, i will be waiting 😄

**Comment by mitsukarenai** [comment]
> mitsukareni, so, i'm using this website that you created bridge.suumitsu.eu, rss bridge, in my bot on discord, and sometimes i receive this error "Bridge returned error 500! (17880)
> 
> [link removed]
> 
> and i want to know, if u can fix that problem, i will be waiting smile

Hi @Bakamorita ,
The link you posted points to server github.com, this obviously won't work.
To report an issue, please submit it on the project's issue tracker instead: https://github.com/RSS-Bridge/rss-bridge/issues
And, yes, the Facebook bridge is one of the least stable of all (or the sheer popularity of it makes user report problems more often). And you guess Facebook really really doesn't like it's user data being extracted, so that's poised to fail increasingly.

**Comment by artob** [comment]
@Bakamorita This really isn't the place for support requests regarding RSS-Bridge.

**Pull request merged**
